// File: api/sf/quote.js
// Hybrid approach: creates a Salesforce Quote (with rich custom header fields)
// AND nested QuoteLineItems for Builder / Connector / Amplifier — one per role with hours > 0.
// Uses the Composite Tree API to create everything in a single transaction.

import { getSession } from "../../lib/session.js";
import { sfFetch } from "../../lib/sfClient.js";

const ENGAGEMENT_LABELS = {
  operational: "Operational",
  strategic: "Strategic",
  ideation: "Ideation",
  execution: "Execution",
};

const TIER_LABELS = {
  execute: "Execute",
  elevate: "Elevate",
  excel: "Excel",
  drive: "Drive",
  amplify: "Amplify",
};

const COMMIT_LABELS = {
  none: "None",
  "3mo": "3 Month",
  "6mo": "6 Month",
  "12mo": "12 Month",
};

// Builder product code varies by engagement type (Strategic/Ideation = $225, Operational = $240, Execution = $225)
const BUILDER_CODE_BY_ENG = {
  operational: "BLD-OP",
  execution: "BLD-EX",
  strategic: "BLD-ST",
  ideation: "BLD-ST",
};

const PRODUCT_CODES = ["BLD-ST", "BLD-OP", "BLD-EX", "CON", "AMP"];

// Look up Standard Pricebook entries for all 5 Delegate products in one query
async function getPricebookEntries(session) {
  const codesIn = PRODUCT_CODES.map(c => `'${c}'`).join(",");
  const soql = `SELECT Id, Product2.ProductCode, Pricebook2Id FROM PricebookEntry WHERE Pricebook2.IsStandard = true AND IsActive = true AND Product2.ProductCode IN (${codesIn})`;
  const result = await sfFetch(session, `/services/data/v60.0/query/?q=${encodeURIComponent(soql)}`);

  const entriesByCode = {};
  let pricebookId = null;
  for (const r of (result?.records || [])) {
    const code = r.Product2?.ProductCode;
    if (code) entriesByCode[code] = r.Id;
    pricebookId = r.Pricebook2Id;
  }
  return { entriesByCode, pricebookId };
}

export default async function handler(req, res) {
  if (req.method !== "POST") return res.status(405).json({ error: "Method not allowed" });

  const session = await getSession(req, res);
  if (!session?.accessToken) return res.status(401).json({ error: "Not authenticated" });

  const {
    opportunityId,
    accountName,
    engagementType,
    tierId,
    tierLabel,
    monthlyInvestment,
    totalHours,
    pillarMultiplier,
    effectiveDiscount, // 0–1
    commitTerm,
    pricingDetail,
    // Per-role hours + unit prices (unit prices already include pillar multiplier and risk buffer)
    builderHours,
    builderUnitPrice,
    connectorHours,
    connectorUnitPrice,
    amplifierHours,
    amplifierUnitPrice,
  } = req.body || {};

  if (!opportunityId) return res.status(400).json({ error: "opportunityId is required" });
  if (monthlyInvestment == null) return res.status(400).json({ error: "monthlyInvestment is required" });

  // Look up Pricebook entries before we build anything else
  let entriesByCode, pricebookId;
  try {
    ({ entriesByCode, pricebookId } = await getPricebookEntries(session));
  } catch (e) {
    return res.status(500).json({ error: `Pricebook lookup failed: ${e.message}` });
  }

  if (!pricebookId || PRODUCT_CODES.some(c => !entriesByCode[c])) {
    const missing = PRODUCT_CODES.filter(c => !entriesByCode[c]);
    return res.status(500).json({
      error: `Missing Salesforce Products in Standard Pricebook. Create products with these codes: ${missing.join(", ")}. See Phase 2 README for setup steps.`,
    });
  }

  // Quote Name
  const today = new Date().toISOString().split("T")[0];
  const tierForName = tierLabel || TIER_LABELS[tierId] || ENGAGEMENT_LABELS[engagementType] || "Quote";
  const name = `Delegate Pricing — ${tierForName} — ${today}`;

  // ExpirationDate: 30 days out
  const exp = new Date();
  exp.setDate(exp.getDate() + 30);
  const expirationDate = exp.toISOString().split("T")[0];

  // Human-readable Quote description (shows in standard SF UI)
  const descriptionLines = [
    `Engagement: ${ENGAGEMENT_LABELS[engagementType] || engagementType}`,
    tierForName ? `Tier: ${tierForName}` : null,
    `Monthly Investment: $${Number(monthlyInvestment).toLocaleString()}`,
    `Total Hours: ${totalHours} hrs/mo`,
    `Pillar Multiplier: ${pillarMultiplier?.toFixed?.(3) ?? pillarMultiplier}x`,
    `Effective Discount: ${(Number(effectiveDiscount) * 100).toFixed(1)}%`,
    `Commit Term: ${COMMIT_LABELS[commitTerm] || commitTerm}`,
    "",
    "Generated by Delegate Pricing Calculator.",
  ].filter(Boolean).join("\n");

  // Build line items — one per role with hours > 0
  // Discount goes on each line item (Quote.Discount is calculated/read-only, rolls up from these)
  const builderCode = BUILDER_CODE_BY_ENG[engagementType] || "BLD-ST";
  const lineDiscount = (Number(effectiveDiscount) || 0) * 100; // 0-100 percent
  const lineItems = [];

  if (Number(builderHours) > 0) {
    lineItems.push({
      attributes: { type: "QuoteLineItem", referenceId: "li_builder" },
      PricebookEntryId: entriesByCode[builderCode],
      Quantity: Number(builderHours),
      UnitPrice: Number(builderUnitPrice).toFixed(4),
      Discount: lineDiscount,
    });
  }
  if (Number(connectorHours) > 0) {
    lineItems.push({
      attributes: { type: "QuoteLineItem", referenceId: "li_connector" },
      PricebookEntryId: entriesByCode["CON"],
      Quantity: Number(connectorHours),
      UnitPrice: Number(connectorUnitPrice).toFixed(4),
      Discount: lineDiscount,
    });
  }
  if (Number(amplifierHours) > 0) {
    lineItems.push({
      attributes: { type: "QuoteLineItem", referenceId: "li_amplifier" },
      PricebookEntryId: entriesByCode["AMP"],
      Quantity: Number(amplifierHours),
      UnitPrice: Number(amplifierUnitPrice).toFixed(4),
      Discount: lineDiscount,
    });
  }

  // Build the composite tree: Quote (with custom fields) + nested QuoteLineItems
  // Note: Quote.Discount is read-only (calculated from line items), so we don't set it here.
  // Each line item carries the Discount, and SF rolls it up to the Quote level.
  const quoteRecord = {
    attributes: { type: "Quote", referenceId: "quote_main" },
    Name: name,
    OpportunityId: opportunityId,
    ExpirationDate: expirationDate,
    Status: "Draft",
    Description: descriptionLines,
    Pricebook2Id: pricebookId,
    Engagement_Type__c: ENGAGEMENT_LABELS[engagementType] || null,
    Tier__c: TIER_LABELS[tierId] || null,
    Monthly_Investment__c: Number(monthlyInvestment) || 0,
    Total_Hours__c: Number(totalHours) || 0,
    Pillar_Multiplier__c: Number(pillarMultiplier) || 1,
    Effective_Discount__c: (Number(effectiveDiscount) || 0) * 100,
    Commit_Term__c: COMMIT_LABELS[commitTerm] || "None",
    Pricing_Detail__c: pricingDetail || "",
  };
  if (lineItems.length > 0) {
    quoteRecord.QuoteLineItems = { records: lineItems };
  }

  // Strip nulls so SF doesn't reject
  Object.keys(quoteRecord).forEach(k => quoteRecord[k] === null && delete quoteRecord[k]);

  const compositeBody = { records: [quoteRecord] };

  try {
    const result = await sfFetch(session, "/services/data/v60.0/composite/tree/Quote", {
      method: "POST",
      body: JSON.stringify(compositeBody),
    });

    if (result?.hasErrors) {
      const errDetail = JSON.stringify(result.results, null, 2);
      return res.status(500).json({ error: "Quote creation failed", details: errDetail });
    }

    const quoteResult = (result?.results || []).find(r => r.referenceId === "quote_main");
    const quoteId = quoteResult?.id;
    if (!quoteId) return res.status(500).json({ error: "Quote created but no Id returned" });

    return res.status(200).json({
      quoteId,
      quoteName: name,
      quoteUrl: `${session.instanceUrl}/lightning/r/Quote/${quoteId}/view`,
      lineItemCount: lineItems.length,
    });
  } catch (e) {
    console.error("Quote create failed:", e.message);
    return res.status(500).json({ error: e.message });
  }
}
